default: attention_example attention rnn simple_shallow_nn shallow_nn_two_var shallow_nn deep_nn deep_nn_class relu sigmoid

attention_example:
  typst compile --format svg attention_example.typ

attention:
  typst compile --format svg attention.typ

rnn:
  typst compile --format svg rnn.typ

simple_shallow_nn:
  typst compile --format svg simple_shallow_nn.typ
  
shallow_nn_two_var:
  typst compile --format svg shallow_nn_two_var.typ

shallow_nn:
  typst compile --format svg shallow_nn.typ

deep_nn:
  typst compile --format svg deep_nn.typ
  
deep_nn_class:
  typst compile --format svg deep_nn_class.typ

relu:
  typst compile --format svg relu.typ

sigmoid:
  typst compile --format svg sigmoid.typ